name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  asdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@707e84f3ee349548310aeabdad0dd3bfcb9b69fa # v1

      - name: Run plugin add
        run: asdf plugin add asdf-faas-cli https://github.com/zekker6/asdf-faas-cli.git

      - name: Run plugin test
        run: asdf plugin test asdf-faas-cli .

      - name: Run install
        run: asdf install asdf-faas-cli latest
